on:
  push:
    branches:
      - master
name: AWS Chalice Action
description: This Github action allows automatated deployment of your AWS Chalice application via Github Actions.
icon: cloud
color: yellow
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: chalice deploy
      uses: 5tigerjelly/chalice-action@v1
      with:
        args: deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1