name: AWS Chalice Action
description: This Github action allows automatated deployment of your AWS Chalice application via Github Actions.
author: Chris Oh <chris@5tigerjelly.com>
branding:
  icon: cloud
  color: yellow
runs:
  using: 'docker'
  image: 'Dockerfile'
